---
- name: Add MySQL database username and password
  hosts: all 
  user: root
  vars_files:
    - "group_vars/{{ ansible_os_family }}.yml"
  #remote_user:  
  sudo: yes 

- name: Add MySQL datbases
  hosts: db
  #remote_user: 
  sudo: yes
  roles:
     - mysql    
